// components/ContentShowcase.tsx
'use client'
import { motion } from 'framer-motion'
import Image from 'next/image'

const contentTypes = [
  {
    platform: 'Instagram',
    items: [
      { image: '/showcase/insta-1.jpg', engagement: '12.4%', genTime: '2.7s' },
      { image: '/showcase/insta-2.jpg', engagement: '18.1%', genTime: '3.1s' }
    ]
  },
  {
    platform: 'TikTok',
    items: [
      { image: '/showcase/tiktok-1.jpg', engagement: '22.6%', genTime: '4.3s' },
      { image: '/showcase/tiktok-2.jpg', engagement: '19.8%', genTime: '3.9s' }
    ]
  }
]

export default function ContentShowcase() {
  return (
    <section className="py-24 bg-gray-900">
      <div className="container mx-auto px-4">
        <motion.div
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          className="max-w-4xl mx-auto text-center mb-16"
        >
          <h2 className="text-4xl font-bold text-white mb-4">
            AI-Curated Excellence
          </h2>
          <p className="text-gray-400">
            Actual content generated by ContentPal's NeuralCore™
          </p>
        </motion.div>

        <div className="space-y-20">
          {contentTypes.map((contentType) => (
            <motion.div
              key={contentType.platform}
              initial={{ x: -50, opacity: 0 }}
              whileInView={{ x: 0, opacity: 1 }}
              className="group"
            >
              <div className="flex items-center gap-4 mb-8">
                <h3 className="text-2xl font-bold text-white">
                  {contentType.platform}
                </h3>
                <div className="h-px bg-gray-700 flex-grow" />
              </div>

              <div className="grid md:grid-cols-2 gap-6">
                {contentType.items.map((item) => (
                  <motion.div
                    key={item.image}
                    whileHover={{ scale: 1.02 }}
                    className="relative rounded-2xl overflow-hidden"
                  >
                    <Image
                      src={item.image}
                      width={600}
                      height={600}
                      alt="AI Generated Content"
                      className="w-full h-auto"
                    />
                    <div className="absolute inset-0 bg-gradient-to-t from-gray-900/90 via-transparent p-6 flex items-end">
                      <div className="flex gap-4 text-white">
                        <div className="bg-white/10 px-4 py-2 rounded-full">
                          {item.engagement} Engagement
                        </div>
                        <div className="bg-white/10 px-4 py-2 rounded-full">
                          Generated in {item.genTime}
                        </div>
                      </div>
                    </div>
                  </motion.div>
                ))}
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  )
}